# Fake Radio - Standalone Makefile for Haiku OS
#
# MeshCore radio simulator for testing Sestriere

NAME = FakeRadio
TYPE = APP
SRCS = \
	FakeRadio.cpp

RDEFS = FakeRadio.rdef

LIBS = be translation tracker $(STDCPPLIBS)

SYSTEM_INCLUDE_PATHS =

LOCAL_INCLUDE_PATHS = .

OPTIMIZE := FULL

LOCALES =

DEFINES =

WARNINGS = ALL

SYMBOLS := FALSE

DEBUGGER := FALSE

COMPILER_FLAGS =

LINKER_FLAGS =

APP_VERSION =

DRIVER_PATH =

## Include the Makefile-Engine
DEVEL_DIRECTORY := /boot/system/develop
include $(DEVEL_DIRECTORY)/etc/makefile-engine
